name: Build JAR with Maven

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Step 3: Build the project with Maven (this will create the .jar file)
    - name: Build with Maven
      run: mvn clean package --file pom.xml
    # Step 4: Upload JAR artifact
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-jar
        path: target/*.jar
